clientes =  [
    {
        "codigo_cliente": 1,
        "nombre_cliente": 'GoldFish Garden',
        "nombre_contacto": 'Daniel G',
        "apellido_contacto": 'GoldFish',
        "telefono": '5556901745',
        "fax": '5556901746',
        "linea_direccion1": 'False Street 52 2 A',
        "linea_direccion2": None,
        "ciudad": 'San Francisco',
        "region": None,
        "pais": 'USA',
        "codigo_postal": '24006',
        "codigo_empleado_rep_ventas": 19,
        "limite_credito": 3000.0
    },
    {
        "codigo_cliente": 3,
        "nombre_cliente": 'Gardening Associates',
        "nombre_contacto": 'Anne',
        "apellido_contacto": 'Wright',
        "telefono": '5557410345',
        "fax": '5557410346',
        "linea_direccion1": 'Wall-e Avenue',
        "linea_direccion2": None,
        "ciudad": 'Miami',
        "region": 'Miami',
        "pais": 'USA',
        "codigo_postal": '24010',
        "codigo_empleado_rep_ventas": 19,
        "limite_credito": 6000.0
    },
    {
        "codigo_cliente": 4,
        "nombre_cliente": 'Gerudo Valley',
        "nombre_contacto": 'Link',
        "apellido_contacto": 'Flaute',
        "telefono": '5552323129',
        "fax": '5552323128',
        "linea_direccion1": 'Oaks Avenue nº22',
        "linea_direccion2": None,
        "ciudad": 'New York',
        "region": None,
        "pais": 'USA',
        "codigo_postal": '85495',
        "codigo_empleado_rep_ventas": 22,
        "limite_credito": 12000.0
    },
    {
        "codigo_cliente": 5,
        "nombre_cliente": 'Tendo Garden',
        "nombre_contacto": 'Akane',
        "apellido_contacto": 'Tendo',
        "telefono": '55591233210',
        "fax": '55591233211',
        "linea_direccion1": 'Null Street nº69',
        "linea_direccion2": None,
        "ciudad": 'Miami',
        "region": None,
        "pais": 'USA',
        "codigo_postal": '696969',
        "codigo_empleado_rep_ventas": 22,
        "limite_credito": 600000.0
    },
    {
        "codigo_cliente": 6,
        "nombre_cliente": 'Lasas S.A.',
        "nombre_contacto": 'Antonio',
        "apellido_contacto": 'Lasas',
        "telefono": '34916540145',
        "fax": '34914851312',
        "linea_direccion1": 'C/Leganes 15',
        "linea_direccion2": None,
        "ciudad": 'Fuenlabrada',
        "region": 'Madrid',
        "pais": 'Spain',
        "codigo_postal": '28945',
        "codigo_empleado_rep_ventas": 8,
        "limite_credito": 154310.0
    },
    {
        "codigo_cliente": 7,
        "nombre_cliente": 'Beragua',
        "nombre_contacto": 'Jose',
        "apellido_contacto": 'Bermejo',
        "telefono": '654987321',
        "fax": '916549872',
        "linea_direccion1": 'C/pintor segundo',
        "linea_direccion2": None,
        "ciudad": 'Getafe',
        "region": 'Madrid',
        "pais": 'Spain',
        "codigo_postal": '28942',
        "codigo_empleado_rep_ventas": 11,
        "limite_credito": 20000.0
    },
    {
        "codigo_cliente": 8,
        "nombre_cliente": 'Club Golf Puerta del hierro',
         
         },
    
    ]